version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ../Kombajn/data/models/llm:/root/.ollama/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  comfyui:
    image: yanwk/comfyui:latest
    container_name: comfyui
    restart: always
    ports:
      - "8188:8188"
    volumes:
      - comfyui_data:/home/user/ComfyUI
      - ../Kombajn/data/models:/home/user/ComfyUI/models
      - ./comfyui/extra_model_paths.yaml:/home/user/ComfyUI/extra_model_paths.yaml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  n8n_data:
  ollama_data:
  comfyui_data:
